name: Forbidden City by DKMH
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06037986185401678
title: Forbidden City by DKMH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e2232a'
    - '#f46e6f'
    - '#8a392e'
    - '#feddd3'
  brandStrength: 0.8700645680073649
  lightness: 0.12903600838035345
  saturation: 0.6199945809785277
  rhythmicContrast: 0.2723412613850087
purpose: []
