name: Forbidden City by DKMH
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49901
title: Forbidden City by DKMH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4fa9ff'
    - '#000000'
    - '#9a311b'
    - '#085459'
    - '#fcb55f'
  brandStrength: 0
  lightness: 0.12903600838035345
  saturation: 0
  rhythmicContrast: 0.2723412613850087
purpose: []
